### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/movie-project-codenchill#9]
- [x] This should contain a list of the latest movies. (see issue #12) 
    - [x] created movielist component (issue #12)
- [x] Clicking on a movie should take the user to the Single Page movie (see issue #8) changes are made there

**Comment by merzoukfatima** [comment]
done
